

server {
    listen 80;
    server_name localhost;

    location /api/ {
        proxy_pass http://api:8000; # Пробрасываем запросы к API
        proxy_set_header Host $host; # передает оригинальный адрес сайта (например, teavibe.ru), который ввел юзер.
        proxy_set_header X-Real-IP $remote_addr; # передает настоящий IP-адрес пользователя
        proxy_set_header X-Forwarded-Proto $scheme; # по какому протоколу пришел юзер — http или https.
    }

    location /docs {
        proxy_pass http://api:8000/docs;
    }

    location /openapi.json {
        proxy_pass http://api:8000/openapi.json;
        proxy_set_header Host $host;
    }

    location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ =404;
    }

}