services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - backend_net
    
  nginx:
    build:
      context: .
      dockerfile: build-app/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    networks:
      - backend_net
