version: '3.8'

services:
  pg:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "chaevarka"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    mem_limit: 512m
    networks:
      - backend_net

  api:
    build:
      context: ./chaevarka-server
    ports:
      - "8000:8000"
    container_name: api
    restart: unless-stopped
    environment:
      - TEA_RUN__HOST
      - TEA_RUN__PORT
      - TEA_DB__URL
      - TEA_DB__ECHO
    volumes:
      - ./chaevarka-server:/app
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge