"""add tea_make table

Revision ID: 5c198eace621
Revises: ba0d85321b8c
Create Date: 2025-09-26 14:54:39.916167

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c198eace621"
down_revision: Union[str, Sequence[str], None] = "ba0d85321b8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tea_make",
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("water", sa.Integer(), nullable=False),
        sa.Column("temperature", sa.Integer(), nullable=False),
        sa.Column("sugar", sa.Integer(), nullable=False),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.Column("time", sa.Integer(), nullable=False),
        sa.Column("tea_cnt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tea_make")
    # ### end Alembic commands ###
