"""create firmware table

Revision ID: 4af4f7450030
Revises: 409c8e1ae1f1
Create Date: 2026-03-22 07:03:20.700493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af4f7450030'
down_revision: Union[str, Sequence[str], None] = '409c8e1ae1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmware',
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('device_prefix', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('firmware')
    # ### end Alembic commands ###
