"""add recipes

Revision ID: 47804089e4e3
Revises: 74827bd0272e
Create Date: 2026-03-24 17:53:11.168590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47804089e4e3'
down_revision: Union[str, Sequence[str], None] = '74827bd0272e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('water_amount', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('tea_amount', sa.Integer(), nullable=False),
    sa.Column('drum_1', sa.Integer(), nullable=False),
    sa.Column('drum_2', sa.Integer(), nullable=False),
    sa.Column('drum_3', sa.Integer(), nullable=False),
    sa.Column('drum_4', sa.Integer(), nullable=False),
    sa.Column('drum_5', sa.Integer(), nullable=False),
    sa.Column('drum_6', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
