"""add online_at to devices

Revision ID: c17bd42beb90
Revises: 5c198eace621
Create Date: 2026-03-10 15:32:31.451977

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c17bd42beb90"
down_revision: Union[str, Sequence[str], None] = "5c198eace621"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices", sa.Column("online_at", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "online_at")
    # ### end Alembic commands ###
