"""add_drums_and_dispense

Revision ID: 74827bd0272e
Revises: 4af4f7450030
Create Date: 2026-03-23 13:02:18.351033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74827bd0272e'
down_revision: Union[str, Sequence[str], None] = '4af4f7450030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drum_config',
    sa.Column('ingredient_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tea_make', sa.Column('water_for_cup', sa.Integer(), nullable=False))
    op.add_column('tea_make', sa.Column('drum_1', sa.Integer(), nullable=False))
    op.add_column('tea_make', sa.Column('drum_2', sa.Integer(), nullable=False))
    op.add_column('tea_make', sa.Column('drum_3', sa.Integer(), nullable=False))
    op.add_column('tea_make', sa.Column('drum_4', sa.Integer(), nullable=False))
    op.add_column('tea_make', sa.Column('drum_5', sa.Integer(), nullable=False))
    op.add_column('tea_make', sa.Column('drum_6', sa.Integer(), nullable=False))
    op.drop_column('tea_make', 'sugar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tea_make', sa.Column('sugar', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tea_make', 'drum_6')
    op.drop_column('tea_make', 'drum_5')
    op.drop_column('tea_make', 'drum_4')
    op.drop_column('tea_make', 'drum_3')
    op.drop_column('tea_make', 'drum_2')
    op.drop_column('tea_make', 'drum_1')
    op.drop_column('tea_make', 'water_for_cup')
    op.drop_table('drum_config')
    # ### end Alembic commands ###
